local addon, Engine = ...
---@type DE
local DE = Engine.Core
local L = Engine.L

local format, ipairs, min, pairs, select, strsplit, tonumber = format, ipairs, min, pairs, select, strsplit, tonumber

---@type raidSpellTable
local RaidSpells = {

    -- Ulgrax-the-devourer
    [434799] = true, -- Carnivorous Contest
    [439502] = true, -- Stalker's Webbing
    [436217] = true, -- Juggernaut-Charge
    [440904] = true, -- Devour
    [439419] = true, -- Stalker's Netting

   -- Ulgrax-the-devourer
    [445518] = true, -- Black Blood
  
}

---@type auraTrackTable
local AurasToTrack = {
 -- Ulgrax-the-devourer
    [347274] = {debuff = true, isFail = true}, -- Annihilating Smash stun
}

local autoGeneratedTracker = DE:GenerateAuraTrackerFromSpells(RaidSpells)
DE:MergeTables(AurasToTrack, autoGeneratedTracker, false)

DE:MergeTables(DE.RaidSpells, RaidSpells)
DE:MergeTables(DE.AuraTracker, AurasToTrack)
